apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-guardian.fullname" . }}
  labels:
    {{- include "k8s-guardian.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.aiApiKey }}
  AI_API_KEY: {{ .Values.secrets.aiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.alert.email.smtp.password }}
  ALERT_EMAIL_PASSWORD: {{ .Values.config.alert.email.smtp.password | b64enc | quote }}
  {{- end }}
