apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-guardian.fullname" . }}
  labels:
    {{- include "k8s-guardian.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "k8s-guardian.selectorLabels" . | nindent 4 }}
